# Generated by Django 5.2.5 on 2025-09-05 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_otherdonation'),
    ]

    operations = [
        migrations.AddField(
            model_name='otherdonation',
            name='category',
            field=models.CharField(choices=[('donate', 'Donate'), ('volunteer', 'Volunteer'), ('partner', 'Partner'), ('sponsor', 'Sponsor'), ('other', 'Other')], default='donate', max_length=20),
        ),
    ]
